CREATE TABLE schedule
(
    id       BIGINT       AUTO_INCREMENT PRIMARY KEY COMMENT '식별자', # 식별자 자동 생성
    todo    VARCHAR(200) NOT NULL COMMENT '할일',
    author VARCHAR(100) NOT NULL COMMENT '작성자명',
    password    VARCHAR(100) NOT NULL COMMENT '비밀번호',
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일' # 업데이트 시 자동 갱신
);